name: Deploy mdsite website to GitHub Pages
on:
  workflow_dispatch: null # allow manual triggering via the actions tab
  push: {branches: [main]}
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we
# want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with: {node-version: '18'}

      - run: 'npx @benchristel/mdsite'

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v2
        with: {path: './docs'}

      - uses: actions/deploy-pages@v2
        id: deployment
